apiVersion: v1
kind: Secret
metadata:
  name: videoapi-secrets
stringData:
  # store the full connection string here; the Deployment references this secret
  default-connection: "Server=db;Port=3306;Database=videoapp;User=video;Password=secret;"
type: Opaque
