apiVersion: v1
kind: Service
metadata:
  name: videoapi
  labels:
    app: videoapi
spec:
  type: ClusterIP
  selector:
    app: videoapi
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
